### ISSUE TITLE
Unusual Current Reading for High Side Switch

### ISSUE THREAD

**Issue by giftofyours** [Infineon/arduino-high-side-switch#1]
Using the example sketch on an Arduino UNO: **BTS700x-hss-advanced**, 
and with the following hardware setup:
(Board: High Current PROFET Shield PG-TSDSO-14, 12V power supply, Load connected to output 1, nothing to output 2)

The switch seems to work well to turn on/off the output. However, the current reading seems to be rather random/inaccurate/unusually high. 
I wonder if I might have missed some settings.

**Output: (note the unusually high current shown, voltage and current when switch 2 is turned on is also strange)**
Serial initialized
Initialization successful!
*** Part A: Single switch operation ***
--> Turning on switch :
1
Reading the current, battery voltage and diagnosis status of switch ...
Current flowing through the switch: 54.53 A
Normal operation!
Current battery voltage : 11.58 V
--> Turning off switch : 1
Reading the current, battery voltage and diagnosis status of switch ...
Current flowing through the switch: 38.90 A
Normal operation!
Current battery voltage : 9.44 V
--> Turning on switch :
2
Reading the current, battery voltage and diagnosis status of switch ...
Current flowing through the switch: 33.70 A
Normal operation!
Current battery voltage : 8.04 V
--> Turning off switch : 2
Reading the current, battery voltage and diagnosis status of switch ...
Current flowing through the switch: 33.47 A
Normal operation!
Current battery voltage : 8.15 V

Appreciate advice or any pointers. 
Thanks!

**Comment by boramonideep** [comment]
Thanks @giftofyours for highlighting this issue. This shall be fixed in the next release.

A hint would be to consider the internal exponential filter at the IS pin interface. A for-loop like iteration, similar to [here](https://github.com/Infineon/arduino-high-side-switch/blob/a831ce6fe9e6190c1486cce42827c338ba625632/examples/BTS700x-hss-single-ch/BTS700x-hss-single-ch.ino#L78) will help in getting a more accurate current reading.
